---

name: Build afafk/adelfunpro.au and push to deploy

on:
  push:
    branches: master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: afafk/adelfunpro.au:latest

  build-and-push-to-pages:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/setup-node@v3
        with:
          node-version: 16

      -
        run: npm i -g sass

      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      -
        name: Build the sass dependencies
        run: make build

      -
        name: Update Cloudflare Pages deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
