---

name: Build afafk/adelfunpro.au and push to deploy

on:
  push:
    branches: master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: afafk/adelfunpro.au:latest

  build-and-push-to-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Use apt to get dependencies
        run: sudo apt-get install -y make sass

      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      -
        name: Build the sass dependencies
        run: make build

      -
        name: Copy build files to another branch
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          git fetch

          files="$(ls -1 index.html index.css *.svg)"
          dir="$(mktemp -d)"
          mv font "$dir"
          mv $files "$dir"

          git reset --hard HEAD

          git checkout deploy

          mv "$dir"/* .

          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push -f origin deploy

          rmdir "$dir"
